# Generated by Django 6.0.7 on 2026-08-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria')),
                ('icone', models.CharField(blank=True, max_length=50, verbose_name='Ícone (Font Awesome)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Ator',
                'verbose_name_plural': 'Categorias de Atores',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do município')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do ator')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do ator')),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='Site do ator')),
                ('contato_email', models.CharField(blank=True, max_length=100, verbose_name='Email de contato')),
                ('contato_telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone de contato')),
                ('eh_parceiro_estrategico', models.BooleanField(default=False, verbose_name='É parceiro estratégico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status do ator')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoriaator', verbose_name='Categoria do ator')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.municipio', verbose_name='Município do ator')),
            ],
            options={
                'verbose_name': 'Ator',
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do especialista')),
                ('area_atuacao', models.CharField(blank=True, max_length=150, verbose_name='Área de atuação')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='especialistas/fotos/', verbose_name='Foto')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('linkedin', models.CharField(blank=True, max_length=200, verbose_name='LinkedIn')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status do especialista')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ator', verbose_name='Instituição vinculada')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do evento')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/hora de início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de fim')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local do evento')),
                ('modalidade', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Modalidade do evento')),
                ('link_inscricao', models.CharField(blank=True, max_length=200, verbose_name='Link de inscrição')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='eventos/capas/', verbose_name='Imagem de capa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.municipio', verbose_name='Município do evento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da startup')),
                ('setor_atuacao', models.CharField(blank=True, max_length=150, verbose_name='Setor de atuação')),
                ('estagio', models.CharField(choices=[('ideacao', 'Ideação'), ('validacao', 'Validação'), ('tracao', 'Tração'), ('escala', 'Escala')], default='ideacao', max_length=20, verbose_name='Estágio da startup')),
                ('data_fundacao', models.DateField(blank=True, null=True, verbose_name='Data de fundação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição da startup')),
                ('site', models.CharField(blank=True, max_length=200, verbose_name='Site da startup')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status da startup')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.municipio', verbose_name='Município da startup')),
            ],
            options={
                'verbose_name': 'Startup',
                'verbose_name_plural': 'Startups',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do projeto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do projeto')),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20, verbose_name='Status do projeto')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('instituicoes', models.ManyToManyField(blank=True, to='app.ator', verbose_name='Instituições do projeto')),
                ('startups', models.ManyToManyField(blank=True, to='app.startup', verbose_name='Startups do projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='CasoSucesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do caso de sucesso')),
                ('resumo', models.CharField(blank=True, max_length=300, verbose_name='Resumo')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='casos_sucesso/', verbose_name='Imagem')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('publicado', models.BooleanField(default=True, verbose_name='Status de publicação')),
                ('ator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ator', verbose_name='Ator relacionado')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.startup', verbose_name='Startup relacionada')),
            ],
            options={
                'verbose_name': 'Caso de Sucesso',
                'verbose_name_plural': 'Casos de Sucesso',
            },
        ),
    ]
