# Generated by Django 6.0.7 on 2026-08-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reuniao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ator',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='atores/logos/', verbose_name='Logo do ator'),
        ),
    ]
