# Generated by Django 6.0.7 on 2026-08-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ator_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do membro')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='membros/fotos/', verbose_name='Foto')),
                ('grupo', models.CharField(blank=True, max_length=200, verbose_name='Grupo(s)/Eixo(s)')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição (cargo, instituição, cidade)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Status do membro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'ordering': ['nome'],
            },
        ),
    ]
