# Generated by Django 6.0.7 on 2026-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='startups/logos/', verbose_name='Logo da startup'),
        ),
    ]
