# Generated by Django 6.0.7 on 2026-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_startup_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialista',
            name='tipo_apoio',
            field=models.CharField(blank=True, choices=[('mentoria', 'Mentoria'), ('consultoria', 'Consultoria'), ('palestra', 'Palestra/Capacitação'), ('networking', 'Networking/Conexões')], max_length=20, verbose_name='Tipo de apoio'),
        ),
    ]
