# Generated by Django 6.0.7 on 2026-09-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_especialista_tipo_apoio'),
    ]

    operations = [
        migrations.AddField(
            model_name='casosucesso',
            name='categoria',
            field=models.CharField(choices=[('startup', 'Startup'), ('instituicao', 'Instituição'), ('parceria', 'Parceria')], default='startup', max_length=20, verbose_name='Categoria'),
        ),
    ]
