# Generated by Django 6.0.7 on 2026-09-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_casosucesso_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casosucesso',
            name='categoria',
            field=models.CharField(choices=[('startup', 'Startup'), ('instituicao', 'Instituição'), ('investimento', 'Investimento'), ('parceria', 'Parceria')], default='startup', max_length=20, verbose_name='Categoria'),
        ),
    ]
