# Generated by Django 6.0.7 on 2026-09-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_casosucesso_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/', verbose_name='Imagem do projeto'),
        ),
    ]
