# Generated by Django 6.0.7 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('workshop', 'Workshop'), ('palestra', 'Palestra'), ('feira', 'Feira')], default='presencial', max_length=20, verbose_name='Tipo de evento'),
        ),
    ]
