# Generated by Django 6.0.7 on 2026-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_evento_tipo_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialista',
            options={'ordering': ['-destaque', 'nome'], 'verbose_name': 'Especialista', 'verbose_name_plural': 'Especialistas'},
        ),
        migrations.AddField(
            model_name='especialista',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Em destaque'),
        ),
    ]
